In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
print(np.version.version)

1.21.5


In [4]:
a = np.random.random((2,3,5))

a

array([[[0.58561696, 0.92863104, 0.7853863 , 0.49546874, 0.60969533],
        [0.84702462, 0.42220816, 0.8521552 , 0.35886797, 0.05193634],
        [0.0801113 , 0.60121478, 0.28838273, 0.96283043, 0.48027916]],

       [[0.47146704, 0.75195948, 0.36569123, 0.12342029, 0.395525  ],
        [0.08754913, 0.73024111, 0.30373201, 0.77120512, 0.20515379],
        [0.24836521, 0.89432839, 0.84276935, 0.35955372, 0.21864359]]])

In [5]:
b = np.ones((5,2,3))

In [6]:
a.size == b.size

True

In [7]:
a.shape, b.shape

((2, 3, 5), (5, 2, 3))

In [8]:
c = np.transpose(b,(1, 2, 0))
c.shape

(2, 3, 5)

In [9]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
d = np.add(a,c)

In [11]:
a

array([[[0.58561696, 0.92863104, 0.7853863 , 0.49546874, 0.60969533],
        [0.84702462, 0.42220816, 0.8521552 , 0.35886797, 0.05193634],
        [0.0801113 , 0.60121478, 0.28838273, 0.96283043, 0.48027916]],

       [[0.47146704, 0.75195948, 0.36569123, 0.12342029, 0.395525  ],
        [0.08754913, 0.73024111, 0.30373201, 0.77120512, 0.20515379],
        [0.24836521, 0.89432839, 0.84276935, 0.35955372, 0.21864359]]])

In [12]:
d

array([[[1.58561696, 1.92863104, 1.7853863 , 1.49546874, 1.60969533],
        [1.84702462, 1.42220816, 1.8521552 , 1.35886797, 1.05193634],
        [1.0801113 , 1.60121478, 1.28838273, 1.96283043, 1.48027916]],

       [[1.47146704, 1.75195948, 1.36569123, 1.12342029, 1.395525  ],
        [1.08754913, 1.73024111, 1.30373201, 1.77120512, 1.20515379],
        [1.24836521, 1.89432839, 1.84276935, 1.35955372, 1.21864359]]])

In [13]:
e = np.multiply(a,c)
e

array([[[0.58561696, 0.92863104, 0.7853863 , 0.49546874, 0.60969533],
        [0.84702462, 0.42220816, 0.8521552 , 0.35886797, 0.05193634],
        [0.0801113 , 0.60121478, 0.28838273, 0.96283043, 0.48027916]],

       [[0.47146704, 0.75195948, 0.36569123, 0.12342029, 0.395525  ],
        [0.08754913, 0.73024111, 0.30373201, 0.77120512, 0.20515379],
        [0.24836521, 0.89432839, 0.84276935, 0.35955372, 0.21864359]]])

In [14]:
d_max = d.max()
d_max

1.962830433210093

In [15]:
d_min = d.min()
d_min

1.05193634497319

In [16]:
d_mean = d.mean()
d_mean

1.5039804512742019

In [17]:
f = np.empty((2,3,5))
f

array([[[0.58561696, 0.92863104, 0.7853863 , 0.49546874, 0.60969533],
        [0.84702462, 0.42220816, 0.8521552 , 0.35886797, 0.05193634],
        [0.0801113 , 0.60121478, 0.28838273, 0.96283043, 0.48027916]],

       [[0.47146704, 0.75195948, 0.36569123, 0.12342029, 0.395525  ],
        [0.08754913, 0.73024111, 0.30373201, 0.77120512, 0.20515379],
        [0.24836521, 0.89432839, 0.84276935, 0.35955372, 0.21864359]]])

In [40]:
a=0
b=0
c=0
for x in d:
    for y in x:
        for z in y:
            if z>d_min and z<d_mean:
                f[a][b][c]=25
            if z>d_mean and z<d_max:
                f[a][b][c]=75
            if z==d_mean:
                f[a][b][c]=50
            if z==d_min:
                f[a][b][c]=0
            if z==d_max:
                f[a][b][c]=100
            c+=1
        c=0
        b+=1
    b=0
    a+=1
print(f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  25.  75.  25.   0.]
  [ 25.  75.  25. 100.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75.  75.  25.  25.]]]


In [41]:
print(d)

[[[1.58561696 1.92863104 1.7853863  1.49546874 1.60969533]
  [1.84702462 1.42220816 1.8521552  1.35886797 1.05193634]
  [1.0801113  1.60121478 1.28838273 1.96283043 1.48027916]]

 [[1.47146704 1.75195948 1.36569123 1.12342029 1.395525  ]
  [1.08754913 1.73024111 1.30373201 1.77120512 1.20515379]
  [1.24836521 1.89432839 1.84276935 1.35955372 1.21864359]]]


In [42]:
print(f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  25.  75.  25.   0.]
  [ 25.  75.  25. 100.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75.  75.  25.  25.]]]
