In [1]:
#help(np)

In [2]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/carlosbasco/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/carlosbasco/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/carlosbasco/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/carlosbasco/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/carlosbasco/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/carlosbasco/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/carlosbasco/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/carlosbasco/opt/anaconda3/include']
Supported SIMD ex

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))

In [5]:
#4. Print a.
a

array([[[0.60944597, 0.61522576, 0.61226521, 0.81305768, 0.43370182],
        [0.91269414, 0.46145254, 0.55554789, 0.45297461, 0.49691576],
        [0.73472385, 0.57297581, 0.54860159, 0.4874207 , 0.41736413]],

       [[0.36359096, 0.4150056 , 0.36142456, 0.53786433, 0.46180499],
        [0.58478655, 0.33404888, 0.06689473, 0.68509435, 0.83364758],
        [0.41022608, 0.1293613 , 0.26827512, 0.72546252, 0.58952105]]])

In [6]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))

In [7]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
#7. Do a and b have the same size? How do you prove that in Python code?

a.size == b.size

True

In [10]:
#8. Are you able to add a and b? Why or why not?

np.add(a,b)
pass
#No permite sumar matrices de dimensiones diferentes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [11]:
#9. Transpose b so that it has the same structure 
#of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b,(1,2,0))

In [12]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
print(a.shape)
print(b.shape)
print(c.shape)

d = np.add(a,c)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


In [13]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)
#Hemos sumado 1.0 a cada elemento de la matriz a y lo hemos guardado en la matriz d

[[[0.60944597 0.61522576 0.61226521 0.81305768 0.43370182]
  [0.91269414 0.46145254 0.55554789 0.45297461 0.49691576]
  [0.73472385 0.57297581 0.54860159 0.4874207  0.41736413]]

 [[0.36359096 0.4150056  0.36142456 0.53786433 0.46180499]
  [0.58478655 0.33404888 0.06689473 0.68509435 0.83364758]
  [0.41022608 0.1293613  0.26827512 0.72546252 0.58952105]]]
[[[1.60944597 1.61522576 1.61226521 1.81305768 1.43370182]
  [1.91269414 1.46145254 1.55554789 1.45297461 1.49691576]
  [1.73472385 1.57297581 1.54860159 1.4874207  1.41736413]]

 [[1.36359096 1.4150056  1.36142456 1.53786433 1.46180499]
  [1.58478655 1.33404888 1.06689473 1.68509435 1.83364758]
  [1.41022608 1.1293613  1.26827512 1.72546252 1.58952105]]]


In [14]:
#12. Multiply a and c. Assign the result to e.

e = np.multiply(a,c)
e

array([[[0.60944597, 0.61522576, 0.61226521, 0.81305768, 0.43370182],
        [0.91269414, 0.46145254, 0.55554789, 0.45297461, 0.49691576],
        [0.73472385, 0.57297581, 0.54860159, 0.4874207 , 0.41736413]],

       [[0.36359096, 0.4150056 , 0.36142456, 0.53786433, 0.46180499],
        [0.58478655, 0.33404888, 0.06689473, 0.68509435, 0.83364758],
        [0.41022608, 0.1293613 , 0.26827512, 0.72546252, 0.58952105]]])

In [15]:
#13. Does e equal to a? Why or why not?

a == e
#Estamos multiplicando los elementos por 1.0 por lo que los valores no varian

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [16]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print (d_max)
print (d_min)
print (d_mean)

1.9126941376455395
1.066894728342144
1.516379201377886


In [17]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))

In [18]:
"""
#16. Populate the values in f. 
For each value in d, 
if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
np.set_printoptions(formatter={"float": lambda x:"%0.6f"%(x)})

print ("d max: ",d_max)
print ("d min: ",d_min)
print ("d mean: ",d_mean)

indice = 0
filas = 0
columnas = 0

for i in d:
    for j in i:
        for k in j:
            if k > d_min and k < d_mean:
                f[indice][filas][columnas] = 25
            elif k > d_mean and k < d_max:
                f[indice][filas][columnas] = 75
            elif k == d_mean:
                f[indice][filas][columnas] = 50
            elif k == d_min:
                f[indice][filas][columnas] = 0
            elif k == d_max:
                f[indice][filas][columnas] = 100
            columnas +=1
        filas +=1
        columnas = 0
    indice +=1
    filas = 0
    columnas = 0

d max:  1.9126941376455395
d min:  1.066894728342144
d mean:  1.516379201377886
d:
[[[1.609446 1.615226 1.612265 1.813058 1.433702]
  [1.912694 1.461453 1.555548 1.452975 1.496916]
  [1.734724 1.572976 1.548602 1.487421 1.417364]]

 [[1.363591 1.415006 1.361425 1.537864 1.461805]
  [1.584787 1.334049 1.066895 1.685094 1.833648]
  [1.410226 1.129361 1.268275 1.725463 1.589521]]]
f:
[[[0.609446 0.615226 0.612265 0.813058 0.433702]
  [0.912694 0.461453 0.555548 0.452975 0.496916]
  [0.734724 0.572976 0.548602 0.487421 0.417364]]

 [[0.363591 0.415006 0.361425 0.537864 0.461805]
  [0.584787 0.334049 0.066895 0.685094 0.833648]
  [0.410226 0.129361 0.268275 0.725463 0.589521]]]
f tras loops:
[[[75.000000 75.000000 75.000000 75.000000 25.000000]
  [100.000000 25.000000 75.000000 25.000000 25.000000]
  [75.000000 75.000000 75.000000 25.000000 25.000000]]

 [[25.000000 25.000000 25.000000 75.000000 25.000000]
  [75.000000 25.000000 0.000000 75.000000 75.000000]
  [25.000000 25.000000 25.000000

In [19]:
#17. Print d and f. Do you have your expected f?
"""
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print("d:")
print(d)
print("f:")
print(f)

#Si.

d:
[[[1.609446 1.615226 1.612265 1.813058 1.433702]
  [1.912694 1.461453 1.555548 1.452975 1.496916]
  [1.734724 1.572976 1.548602 1.487421 1.417364]]

 [[1.363591 1.415006 1.361425 1.537864 1.461805]
  [1.584787 1.334049 1.066895 1.685094 1.833648]
  [1.410226 1.129361 1.268275 1.725463 1.589521]]]
f:
[[[75.000000 75.000000 75.000000 75.000000 25.000000]
  [100.000000 25.000000 75.000000 25.000000 25.000000]
  [75.000000 75.000000 75.000000 25.000000 25.000000]]

 [[25.000000 25.000000 25.000000 75.000000 25.000000]
  [75.000000 25.000000 0.000000 75.000000 75.000000]
  [25.000000 25.000000 25.000000 75.000000 75.000000]]]


In [25]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
indice = []
filas = []
columnas = []

for i in d:
    for j in i:
        for k in j:
            if k > d_min and k < d_mean:
                columnas.append("B")
            elif k > d_mean and k < d_max:
                columnas.append("D")
            elif k == d_mean:
                columnas.append("C")
            elif k == d_min:
                columnas.append("A")
            elif k == d_max:
                columnas.append("E")
        filas.append(columnas)
        columnas = []
    indice.append(filas)
    filas = []
    columnas = []
    
print("d:")
print(d)
print("f:")
print(f)
print()
print("array con letras:")
print(indice)

d:
[[[1.609446 1.615226 1.612265 1.813058 1.433702]
  [1.912694 1.461453 1.555548 1.452975 1.496916]
  [1.734724 1.572976 1.548602 1.487421 1.417364]]

 [[1.363591 1.415006 1.361425 1.537864 1.461805]
  [1.584787 1.334049 1.066895 1.685094 1.833648]
  [1.410226 1.129361 1.268275 1.725463 1.589521]]]
f:
[[[75.000000 75.000000 75.000000 75.000000 25.000000]
  [100.000000 25.000000 75.000000 25.000000 25.000000]
  [75.000000 75.000000 75.000000 25.000000 25.000000]]

 [[25.000000 25.000000 25.000000 75.000000 25.000000]
  [75.000000 25.000000 0.000000 75.000000 75.000000]
  [25.000000 25.000000 25.000000 75.000000 75.000000]]]

array con letras:
[[['D', 'D', 'D', 'D', 'B'], ['E', 'B', 'D', 'B', 'B'], ['D', 'D', 'D', 'B', 'B']], [['B', 'B', 'B', 'D', 'B'], ['D', 'B', 'A', 'D', 'D'], ['B', 'B', 'B', 'D', 'D']]]
