In [1]:
#1. Import the NUMPY package under the name np.

%pip install numpy
import numpy as np
import warnings
warnings.filterwarnings('ignore')

Note: you may need to restart the kernel to use updated packages.


In [2]:
#2. Print the NUMPY version and the configuration.

print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Usuario/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Usuario/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Usuario/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Usuario/anaconda3\\Library\\include']
Supported SIMD extensions in 

In [14]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
#Print a

a = np.random.random_sample((2,3,5))
x = np.random.randint(1,100, size=(2,3,5))
j = np.random.random_integers(10, size=(2,3,5))

print('matriz a: ','\n', a,'\n\nmatriz b:','\n', x, '\n\nmatric c:', '\n',j)

matriz a:  
 [[[2.67641985e-01 2.80781511e-01 4.02466403e-01 5.47769549e-01
   1.82834054e-01]
  [9.04148771e-01 1.10086956e-01 7.92790732e-01 4.39351391e-01
   5.59266482e-01]
  [7.20740282e-01 2.32017354e-02 2.76528765e-01 5.76061208e-01
   4.56419992e-01]]

 [[5.45988929e-04 3.99522539e-01 3.38768402e-01 1.76138173e-01
   6.48658222e-02]
  [9.49515078e-01 5.52421664e-01 2.16615142e-01 5.73266398e-01
   5.78898730e-01]
  [2.76715811e-01 2.18792774e-01 3.45196758e-01 8.39241869e-01
   5.51844156e-01]]] 

matriz b: 
 [[[52 59 63 16 87]
  [12 74 22 54  8]
  [61 50 64 66 12]]

 [[53 14 23 94 47]
  [69 77 65 43 45]
  [21 26 37 99 65]]] 

matric c: 
 [[[ 7  4  9  6  2]
  [ 1  6 10  9  7]
  [ 1  2  3  5  1]]

 [[ 6  3  5  5  1]
  [ 6  5  6 10  6]
  [ 9  8  1  3  2]]]


In [11]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#6. Print b.

b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [5]:
#7. Do a and b have the same size? How do you prove that in Python code?

print('size a:', a.size, '//', 'size b:', b.size)

size a: 30 // size b: 30


In [6]:
a.size == b.size

True

In [7]:
#8. Are you able to add a and b? Why or why not? No, bc they don't have the same shape.

a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
print('shape a:', a.shape, '//', 'shape b:', b.shape)

In [15]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.transpose(1,2,0)
print(c, '\n\nshape:',c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 

shape: (2, 3, 5)


In [16]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now? They have the same size.

d = a + c
d

array([[[1.26764199, 1.28078151, 1.4024664 , 1.54776955, 1.18283405],
        [1.90414877, 1.11008696, 1.79279073, 1.43935139, 1.55926648],
        [1.72074028, 1.02320174, 1.27652876, 1.57606121, 1.45641999]],

       [[1.00054599, 1.39952254, 1.3387684 , 1.17613817, 1.06486582],
        [1.94951508, 1.55242166, 1.21661514, 1.5732664 , 1.57889873],
        [1.27671581, 1.21879277, 1.34519676, 1.83924187, 1.55184416]]])

In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain. La matriz d es la matriz a + 1

print('matriz a:','\n',a)
print('\nmatriz d','\n',d)

In [ ]:
#12. Multiply a and c. Assign the result to e.

e = a*c
e

In [ ]:
#13. Does e equal to a? Why or why not?

'''
Sí, son iguales porque en esta operación c es el elemento neutro de a.
'''

In [18]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print('max:',d_max)
print('min:',d_min)
print('mean:',d_mean)

max: 1.9495150778197128
min: 1.000545988929047
mean: 1.4207479706925576


In [39]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.zeros((2, 3, 5))
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [30]:
d

array([[[1.26764199, 1.28078151, 1.4024664 , 1.54776955, 1.18283405],
        [1.90414877, 1.11008696, 1.79279073, 1.43935139, 1.55926648],
        [1.72074028, 1.02320174, 1.27652876, 1.57606121, 1.45641999]],

       [[1.00054599, 1.39952254, 1.3387684 , 1.17613817, 1.06486582],
        [1.94951508, 1.55242166, 1.21661514, 1.5732664 , 1.57889873],
        [1.27671581, 1.21879277, 1.34519676, 1.83924187, 1.55184416]]])

In [37]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
"""If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for x in range(d.shape[0]):
    
    for y in range(d.shape[1]):
        
        for z in range(d.shape[2]):
            
            if d_mean > d[x][y][z] > d_min:
                f[x][y][z] = 25
                
            elif (d_max > d[x][y][z] > d_mean):
                f[x][y][z] = 75
                
            elif d[x][y][z] == d_mean:
                f[x][y][z] = 50
            
            elif d[x][y][z] == d_min:
                f[x][y][z] = 0
            
            elif d[x][y][z] == d_max:
                f[x][y][z] = 100

#17. Print d and f. Do you have your expected f?
print(f)

[[[ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[  0.  25.  25.  25.  25.]
  [100.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.  75.]]]


In [59]:
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [75]:
lst = [] 

for i in range(3):
    lst.append(['A']) 
    for j in range(5): 
        lst[i].append('B') 
        
lst2 = []
for i in range(3):
    lst2.append(['C']) 
    for j in range(5): 
        lst2[i].append('D')
        
list_g = [lst,lst2]

        
print(list_g) 

[[['A', 'B', 'B', 'B', 'B', 'B'], ['A', 'B', 'B', 'B', 'B', 'B'], ['A', 'B', 'B', 'B', 'B', 'B']], [['C', 'D', 'D', 'D', 'D', 'D'], ['C', 'D', 'D', 'D', 'D', 'D'], ['C', 'D', 'D', 'D', 'D', 'D']]]


In [76]:
np.array(list_g)

array([[['A', 'B', 'B', 'B', 'B', 'B'],
        ['A', 'B', 'B', 'B', 'B', 'B'],
        ['A', 'B', 'B', 'B', 'B', 'B']],

       [['C', 'D', 'D', 'D', 'D', 'D'],
        ['C', 'D', 'D', 'D', 'D', 'D'],
        ['C', 'D', 'D', 'D', 'D', 'D']]], dtype='<U1')

In [88]:
# #18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements?

for x in range(d.shape[0]):
    
    for y in range(d.shape[1]):
        
        for z in range(d.shape[2]):
            
            if d_mean > d[x][y][z] > d_min:
                list_g[x][y][z] = 'B'
                
            elif (d_max > d[x][y][z] > d_mean):
                list_g[x][y][z] = 'D'
                
            elif d[x][y][z] == d_mean:
                list_g[x][y][z] = 'C'
            
            elif d[x][y][z] == d_min:
                list_g[x][y][z] = 'A'
            
            elif d[x][y][z] == d_max:
                list_g[x][y][z] = 'E'
                
list_g

[[['B', 'B', 'B', 'D', 'B', 'B'],
  ['D', 'B', 'D', 'D', 'D', 'B'],
  ['D', 'B', 'B', 'D', 'D', 'B']],
 [['A', 'B', 'B', 'B', 'B', 'D'],
  ['E', 'D', 'B', 'D', 'D', 'D'],
  ['B', 'B', 'B', 'D', 'D', 'D']]]